#locators using id
############################################################
id:

#locators using name
############################################################
name:
 #Login page

 back_office.login_page.user-name-element: 'j_username'
 back_office.login_page.password-element: 'j_password'

 back_office.login_page.password: 'j_password'
 back_office.login_page.user-name-element: 'j_username'
 back_office.login_page.password-element: 'j_password'


 #locators using css
############################################################
css:
 #Login page

 back_office.login_page.user-name-element: '.login.z-textbox'

 back_office.login_page.login-button-element: '.login_btn'
 back_office.login_page.pop-up-window: '.z-messagebox-button.z-button'
 back_office.login_page.pop-up-window-close-button: '.webkit.webkit1.breeze div:nth-child(13) div:nth-child(1) div i'

 back_office.login_page.pop-up-window-close-button: '.z-messagebox-button.z-button'
 back_office.home-page_reserve: '.z-listbox div'
 back_office.login_page.pop-up-window-close-button: '.webkit.webkit1.breeze div:nth-child(13) div:nth-child(1) div i'
 
 #Home Page
 back_office.home_page.search-order-link: 'z-label'
 back_office.home-page.search-order-id-text-box: '.search-area.z-textbox'
 back_office.home-page.search-button: '.search-button.z-button'
 back_office.home-page.searched-element: 'z-label'
 back_office.home-page.order-status: '.z-listitem'
 back_office.home-page.seller-id: '.z-label'
 back_office.home-page.seller-name: 'z-label'
 back_office.home-page.awb-number: 'z-label'
 back_office.home-page.search-by-ussid-link: '.yw-navigationNode-level1.z-treerow.z-treerow-selected .yw-treeCellInner.z-div'
 back_office.home-page.ussid-number: '.z-treechildren tr:nth-child(5) td div div span' 
 back_office.home-page.ussid text area: .z-hbox tbody tr td table tbody tr td:nth-child(3) input
 back_office.home-page.ussid search: .z-hbox tbody tr td table tbody tr td:nth-child(5) button 
 back_office.home-page.search-order-link: '.z-treechildren tr:nth-child(6) td div div span'
 back_office.home-page.search-button: //*[starts-with(@class, 'z-columnchildren-content')]/div[1]/div[1]/div[1]/div[1]/div[3]/button
 back_office.home-page.searched-element: '.mylist.z-listbox div:nth-child(4) table tbody tr'
 back_office.home-page.order-status: '.orderlines_list.z-listbox div:nth-child(4) table tbody tr td:nth-child(2)'
 back_office.home-page.seller-id: '.z-columnchildren-content div:nth-child(3) div:nth-child(2) div div:nth-child(5) div:nth-child(6)  div div:nth-child(3)'
 back_office.home-page.seller-name: '.z-panelchildren.z-panelchildren-noborder div:nth-child(3) div:nth-child(2) div div:nth-child(3)'
 back_office.home-page.parent-feeder-slave-name: '.z-panelchildren.z-panelchildren-noborder div:nth-child(3) div:nth-child(4) div div:nth-child(3)'
 back_office.home-page.awb-number: '.z-columnchildren-content div:nth-child(3) div:nth-child(2) div div:nth-child(5) div:nth-child(5)  div div:nth-child(3)'
 back_office.home-page.search-by-ussid-link: '.yw-navigationNode-level1.z-treerow.z-treerow-selected .yw-treeCellInner.z-div'
 back_office.home-page.ussid-number: '.z-treechildren tr:nth-child(5) td div div span' 
 back_office.home-page.ussid search: '.z-hbox tbody tr td table tbody tr td:nth-child(5) button' 
 back_office.home-page.ok: '.z-hbox tbody tr td table tbody tr td button'
 back_office.home-page.order id-select: '.mylist.z-listbox div:nth-child(4) table tbody tr'
 back_office.home-page.order id value: '.mylist.z-listbox div:nth-child(4) table tbody tr td:nth-child(1) div span'
 back_office.home-page.order allocated: '.orderlines_list.z-listbox div:nth-child(4) table tbody tr td:nth-child(2)' 
  
 back_office.home-page.ussid-search: '.z-hbox tbody tr td table tbody tr td:nth-child(5) button' 
 back_office.home-page.ussid-text-area: '.z-hbox tbody tr td table tbody tr td:nth-child(3) input'
 back_office.home-page.select-slave-name: '.z-panelchildren.z-panelchildren-noborder div:nth-child(3) div:nth-child(1) div div:nth-child(3) select'
 back_office.home-page.save-slave-name: '.z-panelchildren.z-panelchildren-noborder div:nth-child(3) div:nth-child(9) div div:nth-child(3)'
 back_office.home-page.update-slave-ok-button: '.z-hbox table tbody tr td button'
 
 #locators using css
############################################################



xpath:
 #Login page
 
 back_office.login_page.password-element: //input[@ytestid='j_password']
 #locators using xpath
############################################################
xpath: 

# Home Page
 back_office.home-page.order-id-number: //td[@class='y-tree-icon-ordersbyorderid z-treecell']
 back_office.home-page.ussid-text-area: //*[starts-with(@class, 'z-hbox')]/tbody[1]/tr[1]/td[1]/table[1]/tbody[1]/tr[1]/td[3]/input
 back_office.home-page.order id-number: //td[@class='y-tree-icon-ordersbyorderid z-treecell']
 back_office.home-page.slave-message: '.z-listbox-body table tbody tr td:nth-child(1)'
 back_office.home-page.reservation-column: '.z-listbox-body table tbody tr td:nth-child(4)'
 back_office.home-page.enter-order-id: //*[starts-with(@class, 'z-columnchildren-content')]/div[1]/div[1]/div[1]/div[1]/div[2]/input

