package com.jda.wms.email;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Map;

import com.google.inject.Inject;
import com.jda.wms.config.Configuration;
import com.jda.wms.context.Context;;

public class HtmlCreator {

	private final Context context;
	private final RequestDetailsRetriever requestDetailsRetriever;
	private final Configuration configuration;

	@Inject
	public HtmlCreator(Configuration configuration, Context context, RequestDetailsRetriever requestDetailsRetriever) {
		this.context = context;
		this.requestDetailsRetriever = requestDetailsRetriever;
		this.configuration = configuration;
	}

	@SuppressWarnings({ "rawtypes" })
	public void htmlWriter(String reqId) {
		String title = configuration.getStringProperty("auto-title");
		Map<String, Object> requestSummaryDetailsMap = requestDetailsRetriever.getRequestparentDetails(reqId);
		String requestSubmittedby = (String) requestSummaryDetailsMap.get("requestSubmittedby");
		String RequestSubmittedOn = (String) requestSummaryDetailsMap.get("RequestSubmittedOn");
		String totalTimeTaken = (String) requestSummaryDetailsMap.get("totalTimeTaken");
		String totalTestsExecuted = (String) requestSummaryDetailsMap.get("totalTestsExecuted");
		String region = (String) requestSummaryDetailsMap.get("Region");
		String application = (String) requestSummaryDetailsMap.get("Server/URL");
		String testingPhase = (String) requestSummaryDetailsMap.get("TestingPhase");

		requestSummaryDetailsMap = requestDetailsRetriever.getRequestFailedInterfaceDetails(requestSummaryDetailsMap);

		String failCount = (String) requestSummaryDetailsMap.get("failCount");
		String passCount = (String) requestSummaryDetailsMap.get("passCount");
		String noRunCount = (String) requestSummaryDetailsMap.get("noRunCount");

		requestSummaryDetailsMap = requestDetailsRetriever.getFailedList(context.getParentRequestId());
		ArrayList totalStepList = (ArrayList) requestSummaryDetailsMap.get("totalStepList");
		ArrayList commentsList = (ArrayList) requestSummaryDetailsMap.get("commentsList");
		ArrayList startTime = (ArrayList) requestSummaryDetailsMap.get("startTime");
		ArrayList endTime = (ArrayList) requestSummaryDetailsMap.get("endTime");
		ArrayList totalTime = (ArrayList) requestSummaryDetailsMap.get("totalTime");
		ArrayList statusList = (ArrayList) requestSummaryDetailsMap.get("statusList");// statusLists

		requestSummaryDetailsMap.put("region", region);
		requestSummaryDetailsMap.put("commentsList", commentsList);

		try (BufferedWriter bw = new BufferedWriter(new FileWriter(".\\results\\TEST_REPORT.html"))) {
			bw.write("<html>\n");
			bw.write("<head>\n");
			bw.write("<meta http-equiv=" + "Content-Language" + "content=" + "en-us>\n");
			bw.write("<meta http-equiv=" + "Content-Type" + "content=" + "text/html; charset=windows-1252" + ">\n");
			bw.write("</head>\n");
			bw.write("<body bgcolor=" + "White" + ">\n");
			bw.write(
					"<marquee width='80%' font color='#33B5FF'>THIS IS AN AUTOMATED EMAIL GENERATED BY AUTO - UI</marquee>\n");
			bw.write("<table border='10' width='800' height='100' style='text-align: center'>\n");
			bw.write("<tbody>\n");
			bw.write("<tr>\n");
			bw.write(
					"<td height='0' style='text-align: center;'><img src='cid:image1' alt='TCS Logo does not exist' width='150' height='100' /></td>\n");
			bw.write("<td height='0' style='text-align: center;' colspan='5' bgcolor='#33B5FF'>\n");
			bw.write("<h1><blink> <span style='color: #060606;'>" + title + "</span></blink> </h1></td>\n");
			bw.write(
					"<td height='0' style='text-align: center;' colspan='15'><img src='cid:image2' alt='M&amp;S Logo does not exist' width='100' height='100' /></td>\n");
			bw.write("</tr>\n");
			bw.write("<tr>\n");

			bw.write("<td height='0' rowspan='3' bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;' ><b>&nbsp;Request Id</b></p>\n");
			bw.write("<p style='color: #060606;'><font  size='6'>&nbsp;" + context.getParentRequestId()
					+ "<font></p>\n");
			bw.write("</td>\n");

			bw.write("<td height='0' bgcolor='#33B5FF' colspan =2>\n");
			bw.write("<p style='color: #060606;text-align: left;' ><b>Req. Submitted On</b></p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0'>\n");
			bw.write("<p style='text-align: left;'>&nbsp;" + RequestSubmittedOn + "</p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0'  bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;text-align: left;'><b>Region</b></p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0' colspan='2' >\n");
			bw.write("<p style='text-align: left;'><b>&nbsp;" + region + "</b></p>\n");
			bw.write("</td>\n");
			bw.write("</tr>\n");
			bw.write("<tr>\n");
			bw.write("<td height='0' bgcolor='#33B5FF' colspan =2>\n");
			bw.write("<p style='color: #060606;text-align: left;' ><b>Req. Submitted By</b></p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0'>\n");
			bw.write("<p style='text-align: left;'>&nbsp;" + requestSubmittedby + "</p>\n");
			bw.write("</td>\n");

			bw.write("<td height='0'  bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;text-align: left;'><b>Testing Phase</b></p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0' colspan='2'>\n");
			bw.write("<p style='text-align: left;'>&nbsp;" + testingPhase + "</p>\n");
			bw.write("</td>\n");
			bw.write("</tr>\n");

			bw.write("<tr>\n");
			bw.write("<td height='0' bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;text-align: left;' ><b>Server/URL</b></p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0' colspan='10'>\n");
			bw.write("<p style='text-align: left;'>&nbsp;" + application + "</p>\n"); // server
			bw.write("</td>\n");
			bw.write("</tr>\n");

			bw.write("<tr>\n");
			bw.write("<td height='0' colspan='19' style='text-align: left;'><b>Automation Test Summary:</b></td>\n");
			bw.write("</tr>\n");
			bw.write("<tr><th  bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;'>&nbsp;Total No. of Test Case</p>\n");
			bw.write("</th>\n<th bgcolor='#33B5FF' colspan='2' >\n");
			bw.write("<p style='color: #060606;'>&nbsp;No of Pass</p>\n");
			bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
			bw.write("<p style='color: #060606;'>&nbsp;No. of Fail</p>\n");

			// bw.write("</th>\n<th bgcolor='#33B5FF' colspan='2'>\n");
			// bw.write("<p style='color: #060606;'>&nbsp;No. of No Run</p>\n");

			bw.write("</th>\n<th colspan='16' bgcolor='#33B5FF' colspan =8 >\n");
			bw.write("<p style='color: #060606;'>&nbsp;Total time taken (in HH:MM:SS)</p>\n");
			bw.write("</th>\n</tr>\n");
			bw.write("<tr>\n");
			bw.write("<td height='0'>\n");
			bw.write("<p>&nbsp;" + totalTestsExecuted + "</p>\n");
			bw.write("</td>\n");
			bw.write("<td height='0' bgcolor='#B5F71E' colspan='2'>\n");
			bw.write("<p>&nbsp;" + passCount + "</p>\n");
			bw.write("</td>\n");

			bw.write("<td height='0' bgcolor='#FFAFAB' >\n");
			bw.write("<p>&nbsp;" + failCount + "</p>\n");
			bw.write("</td>\n");

			// bw.write("<td height='0' bgcolor='#DCDEDA' colspan='2'>\n");
			// bw.write("<p>&nbsp;" + noRunCount + "</p>\n");
			// bw.write("</td>\n");

			bw.write("<td height='0' colspan='16'>\n");
			bw.write("<p>&nbsp;" + totalTimeTaken + "</p>\n");
			bw.write("</td>\n");
			bw.write("</tr>\n");

			int totalCount = (Integer.valueOf(failCount) + Integer.valueOf(passCount));

			// System.out.println(totalCount);

			if ((totalStepList.size() == commentsList.size()) && (totalStepList.size() == statusList.size()))

			{
				if (totalStepList.size() == 0) {

				} else {

					bw.write("<tr><th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;S.No</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;Test Case Name</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;Status</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;Start Time</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;End Time</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'>\n");
					bw.write("<p style='color: #060606;'>&nbsp;Total Time</p>\n");

					bw.write("</th>\n<th bgcolor='#33B5FF'  >\n");
					bw.write("<p style='color: #060606;'>&nbsp;Remarks</p>\n");
					bw.write("</th>\n</tr>\n");

					for (int rowCount = 0; rowCount < totalCount; rowCount++) {
						System.out.println("" + totalStepList);
						bw.write("<td>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ (rowCount + 1) + "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");

						bw.write("<td>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ totalStepList.get(rowCount)
								+ "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");

						if (statusList.get(rowCount).toString().contains("PASS")) {
							bw.write(
									"<td bgcolor='#B5F71E'><p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
											+ statusList.get(rowCount)
											+ "</font><font face= Copperplate Gothic Bold></font> </p></td>\n");
						}
						if (statusList.get(rowCount).toString().contains("FAIL")) {
							bw.write(
									"<td bgcolor='#FFAFAB'><p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
											+ statusList.get(rowCount)
											+ "</font><font face= Copperplate Gothic Bold></font> </p></td>\n");
						}

						bw.write("<td>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ startTime.get(rowCount)
								+ "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");

						bw.write("<td>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ endTime.get(rowCount) + "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");

						bw.write("<td>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ totalTime.get(rowCount)
								+ "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");

						bw.write("<td colspan=2>\n");
						bw.write("<p align=center><font color=#060606 size=2 face= Copperplate Gothic Bold>&nbsp;"
								+ commentsList.get(rowCount)
								+ "</font><font face= Copperplate Gothic Bold></font> </p>\n");
						bw.write("</td>\n");
						bw.write("</tr>\n");
					}
					bw.write("</table>\n");
				}
			}
			bw.write("<br>\n");
			bw.write("<br>\n");
			bw.write("<br>\n");
			bw.write("</tbody>\n");
			bw.write("</table>\n");
			bw.write("</body>\n");
			bw.write("</html>\n");
			bw.newLine();
			bw.close();
		} catch (IOException e) {
			e.getStackTrace().toString();
		}

	}

}
