# Default settings
##################
default:
 browser-name: ie
 username: 'AUTO1'
 bck-userid: 'AUTO2'
 password: '1234'

 auto-title: 'JDA C&H Test Automation Result'
 ur.l: 'http://hlxc0dc034.unix.marksandspencercate.com:8880/jdacuat/UserLogin.html' 
 alm-domain: 'GM'
 alm-executed: '19'
 alm-projectName: 'Testing'
 test-caseExecutedManual: '0'
 test-newlyDevelopedCase: '0'
 tbl-RequestBy: 'Kiruthika.Srinivasan'
 tbl-RequestedEmail: 'Kiruthika.Srinivasan@mnscorp.net'
 tbl-parentcluster: '1'
 tbl-parentprojectcode: 'CNH001'
 tbl-parentprojectname: 'JDA Dispatcher Fourwall'
# emailList: 'Kiruthika.Srinivasan@mnscorp.net'
 emailList: 'Santhosh.Narayanaswamy@mnscorp.net,Ramachandra.R.V.Rao@mnscorp.net,Vijay.moses@mnscorp.net,Kiruthika.Srinivasan@mnscorp.net,Santhaseelan.Shanmugam@mnscorp.net,Fathima.Jaseela@mnscorp.net,Indira.Sankaran@mnscorp.net,KumariDivya.Chandan@mnscorp.net,Bhubaneswar.Sethi@mnscorp.net,Raguram.Ramaswamy@mnscorp.net'
 tbl-parentautomationsuitname: '2'
 tbl-parentregion: 'CATE'
 tbl-testingPhase: '14'
 sqlDB-host: 'jdbc:sqlserver://MSHSRMNSUKC0117'
 sqlDB-databaseName: 'NPS_DEV'
 sqlDB-username: 'NPS_TEST' 
 sqlDB-password: 'Webservice2017'
 db-mnsEmailHost: 'mshsrmnsexc0001.mnsexchangecate.adrootcate.marksandspencercate.com'
 db-mnsEmailPort: '25'
 db-mnsEmailFrom: 'mnsukcate\\y0137206'
 db-mnsEmailPassword: 'W!sd0m95'
 cucumber-path: 'D:\\Program Files\\Jenkins\\workspace\\JDA_WMS_GM_Timed\\Cucumber-Reports'
 cucumber-zip-path: 'D:\\Program Files\\Jenkins\\workspace\\JDA_WMS_GM_Timed\\files'
 wst-gm-jda-url: 'http://hlxc0dc034.unix.marksandspencercate.com:8880/jdacuat/UserLogin.html'
 wst-putty-gm-host: 'hlxc0dc035.unix.marksandspencercate.com'
 wst-putty-gm-port-vehicle-load: '24004'
 wst-putty-gm-port: '24005'
 wst-db-host: 'jdbc:oracle:thin:@10.128.177.80:1521:JDACUAT'
 wst-db-username: 'dcsdba'
 wst-db-password: 'dcsabd'
 stk-gm-jda-url: 'http://hlxc0dc034.unix.marksandspencercate.com:8880/jdastkc/UserLogin.html'
 stk-putty-gm-host: 'hlxc0dc035.unix.marksandspencercate.com'
 stk-putty-gm-port: '22902'
 stk-db-host: 'jdbc:oracle:thin:@10.128.177.80:1521:JDASTKC'
 stk-db-username: 'dcsdba'
 stk-db-password: 'jdadccate5'

 


# Browser settings
##################
chrome: &chrome
 browser-name: chrome
    
ie: &ie
 browser-name: ie
 
firefox: &firefox
 browser-name: firefox 

# Test Envoronment settings
###########################
st: &st
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'

sit: &sit

 username: 'p9134817'
 password: '12345'
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'
 
uat: &uat

 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

# Profile settings
##################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie

dev-sit-firefox:
 <<: *sit
 <<: *firefox
     
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie
