# Default settings
##################
default:
 browser-name: ie
 username: 'sarwan'
 password: 'pass'
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20140'
      
# Browser settings
##################
chrome: &chrome
 browser-name: chrome
    
ie: &ie
 browser-name: ie
 
firefox: &firefox
 browser-name: firefox 

# Test Envoronment settings
###########################
st: &st
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20140'

sit: &sit
 username: 'p9121154'
 password: '12345'
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20140'
 
uat: &uat
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

# Profile settings
##################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie

dev-sit-firefox:
 <<: *sit
 <<: *firefox
     
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie