# Default settings
##################
default:
 browser-name: ie
 sit-username: 'AUTOREG2'
 sit-password: '1234' 
# 
 st-username: 'AUTOREG2'
 st-password: '1234' 

 #st-username: 'AUTOREG9'
 #st-password: '1234' 

# 
 
 
 st-Exit-url: 'http://hlxc00dc060.unix.marksandspencercate.com:8880/jdaextc1/UserLogin.html'
 st-putty-Exit-host: 'hlxc00dc061.unix.marksandspencercate.com'
 st-putty-Exit-port: '25312'
 st-db-host: 'jdbc:oracle:thin:@hlxc00dc062.unix.marksandspencercate.com:1521:JDAEXTC1'
 st-db-username: 'dcsdba'
 st-db-password: 'dcsabd'
 
 sit-Exit-url: 'http://hlxc00dc060.unix.marksandspencercate.com:8880/jdaextc1/UserLogin.html'
 sit-putty-Exit-host: 'hlxc00dc061.unix.marksandspencercate.com'
 sit-putty-Exit-port: '25312'
 sit-db-host: 'jdbc:oracle:thin:@hlxc00dc062.unix.marksandspencercate.com:1521:JDAEXTC1'
 sit-db-username: 'dcsdba'
 sit-db-password: 'dcsabd'
 
 auto-title: 'JDA WMS EXIT'
 url: 'http://hlxc00dc060.unix.marksandspencercate.com:8880/jdaextc1/UserLogin.html'
 alm-domain: 'CNH'
 alm-executed: '19'
 test-caseExecutedManual: '0'
 test-newlyDevelopedCase: '0'
 tbl-RequestBy: 'Bhubaneswar.Sethi'
 tbl-RequestedEmail: 'Bhubaneswar.Sethi@mnscorp.net'
 emailList: 'Bhubaneswar.Sethi@mnscorp.net,Sagorika.Samanta@mnscorp.net,priyanka.selvaraj@marks-and-spencer.com'
# emailList: 'Ramachandra.R.V.Rao@mnscorp.net,Vijay.moses@mnscorp.net,Kiruthika.Srinivasan@mnscorp.net,Santhaseelan.Shanmugam@mnscorp.net,Indirakumar.Palanisamy@mnscorp.net,Fathima.Jaseela@mnscorp.net,Indira.Sankaran@mnscorp.net,KumariDivya.Chandan@mnscorp.net,Bhubaneswar.Sethi@mnscorp.net,Raguram.Ramaswamy@mnscorp.net'
 tbl-parentcluster: '2'
 tbl-parentprojectcode: 'CNH'
 tbl-parentprojectname: 'JDA WMS CoE'
 alm-projectName: 'Testing'
 tbl-parentautomationsuitname: '2'
 tbl-parentregion: 'EXIT'
 tbl-testingPhase: '14'
 sqlDB-host: 'jdbc:sqlserver://MSHSRMNSUKC0117'
 sqlDB-databaseName: 'NPS_TEST'
 sqlDB-username: 'NPS_TEST' 
 sqlDB-password: 'Webservice2017'
 db-mnsEmailHost: '10.128.3.46'
 db-mnsEmailPort: '25'
 db-mnsEmailFrom: 'mnsuk\\y0137206'
 db-mnsEmailPassword: 'R*C2duBX'
 #cucumber-path: 'D:\\Program Files\\Jenkins\\workspace\\JDA_WMS_Foods_Timed\\Cucumber-Reports'
 #cucumber-zip-path: 'D:\\Program Files\\Jenkins\\workspace\\JDA_WMS_Foods_Timed\\files'
 cucumber-path: 'Cucumber-Reports'
 cucumber-zip-path: 'files'
      
# Browser settings
##################
chrome: &chrome
 browser-name: chrome
 db-host: 'jdbc:oracle:thin:@10.128.177.80:1521:JDACUAT'
 db-username: 'dcsdba'
 db-password: 'dcsabd'
 url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
    
ie: &ie
 browser-name: ie
 
firefox: &firefox
 browser-name: firefox 

# Test Envoronment settings
###########################
st: &st
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'

sit: &sit

 username: 'p9135145'
 password: '12345'

 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'
 
uat: &uat
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

# Profile settings
##################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie

dev-sit-firefox:
 <<: *sit
 <<: *firefox
     
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie
