########################################################################
# Default settings
########################################################################
default:
 browser-name: chrome
 auth-username: 'siteadmin'
 auth-password: 'ASDF!@#$asdf1234' 
 commerce-base-url: 'https://int.tataunistore.com/store'
 commerce-user-name: ranjith.arumugam@tcs.com
 commerce-password: Ran@1234
      
########################################################################  
# Browser settings
########################################################################
chrome: &chrome
 browser-name: chrome
    
ie: &ie
 browser-name: ie

########################################################################
# Test Envoronment settings
########################################################################
st: &st
 browser-name: chrome
 auth-username: 'siteadmin'
 auth-password: 'ASDF!@#$asdf1234' 
 commerce-base-url: 'https://int.tataunistore.com/store'
 commerce-user-name: ranjith.arumugam@tcs.com
 commerce-password: Ran@1234

sit: &sit
 browser-name: chrome
 auth-username: 'siteadmin'
 auth-password: 'ASDF!@#$asdf1234' 
 commerce-base-url: 'https://int.tataunistore.com/store'
 commerce-user-name: ranjith.arumugam@tcs.com
 commerce-password: Ran@1234
 
uat: &uat
 browser-name: chrome
 auth-username: 'siteadmin'
 auth-password: 'ASDF!@#$asdf1234' 
 commerce-base-url: 'https://int.tataunistore.com/store'
 commerce-user-name: ranjith.arumugam@tcs.com
 commerce-password: Ran@1234

########################################################################  
# Profile settings
########################################################################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie
    
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie