# Default settings
##################
default:
 browser-name: ie
 auth-username: 'xxxxxx'
 auth-password: '12345'
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
      
# Browser settings
##################
chrome: &chrome
 browser-name: chrome
    
ie: &ie
 browser-name: ie

# Test Envoronment settings
###########################
st: &st
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

sit: &sit
 username: 'xxxxxxx'
 password: '12345' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 
uat: &uat
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

# Profile settings
##################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie
    
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie