# Default settings
##################
default:
 browser-name: ie
 username: 'P9135235'
 password: '1234'

 gm-jda-url: 'http://hlxc0dc034.unix.marksandspencercate.com:8880/jdacuat/UserLogin.html'

 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-gm-host: 'hlxc0dc035.unix.marksandspencercate.com'
 putty-gm-port: '24003'
 #putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 #putty-foods-port: '20140'
 db-host: 'jdbc:oracle:thin:@10.128.177.80:1521:JDACUAT'
 db-username: 'dcsdba'
 db-password: 'dcsabd'
 

      
# Browser settings
##################
chrome: &chrome
 browser-name: chrome
    
ie: &ie
 browser-name: ie
 
firefox: &firefox
 browser-name: firefox 

# Test Envoronment settings
###########################
st: &st
 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'

sit: &sit

 username: 'p9134817'
 password: '12345'

 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20254'
 
uat: &uat

 username: 'xxxxxxx'
 password: 'xxxxxxx' 
 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/#'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'

# Profile settings
##################
dev-st-chrome:
 <<: *st
 <<: *chrome

dev-st-ie:
 <<: *st
 <<: *ie
  
dev-sit-chrome:
 <<: *sit
 <<: *chrome

dev-sit-ie:
 <<: *sit
 <<: *ie

dev-sit-firefox:
 <<: *sit
 <<: *firefox
     
dev-uat-chrome:
 <<: *uat
 <<: *chrome

dev-uat-ie:
 <<: *uat
 <<: *ie