# Default settings
##################
default:
 browser-name: ie
 username: 'P9120368'
 password: '12345'

 gm-jda-url: 'http://hlxc0dc012.unix.marksandspencercate.com:8880/#'
 gm-foods-url: 'http://hlxc0dc023.unix.marksandspencercate.com:8880/wmsbac2/UserLogin.html'
 gm-xdoc-url: 'http://hlxc0dc020.unix.marksandspencercate.com:8880/#'
 putty-foods-host: 'hlxc0dc024.unix.marksandspencercate.com'
 putty-foods-port: '20140'
 db-host: 'jdbc:oracle:thin:@10.128.177.64:1521:WMSBAC2'
 db-username: 'dcsdba'
 db-password: 'dcsabd'
